[project]
name = "ai-demos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "faker==37.12.0",
    "numpy==2.3.4",
    "pandas==2.3.3",
    "scikit-learn==1.7.2",
    "scipy==1.16.3",
]

[tool.uv]
# Default to exact version bounds when adding dependencies
add-bounds = "exact"
